services:
  - type: web
    name: personal-website
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python init_db.py
      python add_sample_data.py
      gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:////data/site.db
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
