services:
  - type: web
    name: personal-website
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      echo "Starting application setup..."
      echo "Current directory: $PWD"
      echo "Python version: $(python --version)"
      echo "Creating data directory..."
      mkdir -p $PWD/data
      echo "Setting permissions..."
      chmod -R 777 $PWD/data
      echo "Starting web server..."
      PYTHONUNBUFFERED=1 gunicorn --workers=4 --threads=4 --timeout=120 --log-level=debug app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: development
      - key: FLASK_DEBUG
        value: "1"
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
