services:
  - type: web
    name: personal-website
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      echo "Starting application setup..."
      echo "Current directory: $PWD"
      echo "Python version: $(python --version)"
      echo "Creating data directory..."
      mkdir -p $PWD/data
      echo "Setting permissions..."
      chmod -R 777 $PWD/data
      echo "Initializing database..."
      PYTHONUNBUFFERED=1 python init_db.py || { echo "Database initialization failed"; exit 1; }
      echo "Adding sample data..."
      PYTHONUNBUFFERED=1 python add_sample_data.py || { echo "Sample data addition failed"; exit 1; }
      echo "Starting web server..."
      PYTHONUNBUFFERED=1 gunicorn app:app --log-level debug --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: development
      - key: FLASK_DEBUG
        value: "1"
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
